- name: roboshop frontend setup
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name : nginx
        state: installed

    - name: Copy the file
      ansible.builtin.copy:
        src: fronted.confi
        dest: /etc/nginx/default.d/roboshop.conf

    - name:  remove directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory


    - name: download and extract appilication
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
