
- name: setup nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: import the  file
  ansible.builtin.import_tasks: app-preq.yml

- name: download nodeJS  dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: import the  file
  ansible.builtin.import_tasks: schema-setup.yml

- name: import the  file
  ansible.builtin.import_tasks: systemd-setup.yml





