- name: setup systemd service
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: start {{ component }} setrvice
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon_reload: yes