- name: copy the repo files
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mangoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mangoDB service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes
